package org.zathura.cuentas.personales;
// Generated 4/04/2012 12:36:59 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CpDetalleMovimiento generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="CP_DETALLE_MOVIMIENTO"
    ,schema="CUENTAPERSONAL"
)
@SequenceGenerator(name = "detallemovimintoIdSec", sequenceName = "SEC_CPDETALLEMOVIMIENTO")
public class CpDetalleMovimiento  implements java.io.Serializable {


     private Long idDetalleMovimiento;
     private CpMovimiento cpMovimiento;
     private Long anno;
     private Long mes;
     private Long valorMovimiento;
     private Long valorPago;
     private String pendiente;
     private Date fehcaRegistro;
     private String observaciones;

    public CpDetalleMovimiento() {
    }

	
    public CpDetalleMovimiento(Long idDetalleMovimiento, CpMovimiento cpMovimiento) {
        this.idDetalleMovimiento = idDetalleMovimiento;
        this.cpMovimiento = cpMovimiento;
    }
    public CpDetalleMovimiento(Long idDetalleMovimiento, CpMovimiento cpMovimiento, Long anno, Long mes, Long valorMovimiento, Long valorPago, String pendiente, Date fehcaRegistro, String observaciones) {
       this.idDetalleMovimiento = idDetalleMovimiento;
       this.cpMovimiento = cpMovimiento;
       this.anno = anno;
       this.mes = mes;
       this.valorMovimiento = valorMovimiento;
       this.valorPago = valorPago;
       this.pendiente = pendiente;
       this.fehcaRegistro = fehcaRegistro;
       this.observaciones = observaciones;
    }
   
     @Id 
     @GeneratedValue(generator = "detallemovimintoIdSec")
     @Column(name="ID_DETALLE_MOVIMIENTO", unique=true, nullable=false, precision=22, scale=0)
    public Long getIdDetalleMovimiento() {
        return this.idDetalleMovimiento;
    }
    
    public void setIdDetalleMovimiento(Long idDetalleMovimiento) {
        this.idDetalleMovimiento = idDetalleMovimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MOVIMIENTO", nullable=false)
    public CpMovimiento getCpMovimiento() {
        return this.cpMovimiento;
    }
    
    public void setCpMovimiento(CpMovimiento cpMovimiento) {
        this.cpMovimiento = cpMovimiento;
    }

    
    @Column(name="ANNO", precision=22, scale=0)
    public Long getAnno() {
        return this.anno;
    }
    
    public void setAnno(Long anno) {
        this.anno = anno;
    }

    
    @Column(name="MES", precision=22, scale=0)
    public Long getMes() {
        return this.mes;
    }
    
    public void setMes(Long mes) {
        this.mes = mes;
    }

    
    @Column(name="VALOR_MOVIMIENTO", precision=22, scale=0)
    public Long getValorMovimiento() {
        return this.valorMovimiento;
    }
    
    public void setValorMovimiento(Long valorMovimiento) {
        this.valorMovimiento = valorMovimiento;
    }

    
    @Column(name="VALOR_PAGO", precision=22, scale=0)
    public Long getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(Long valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="PENDIENTE", length=1)
    public String getPendiente() {
        return this.pendiente;
    }
    
    public void setPendiente(String pendiente) {
        this.pendiente = pendiente;
    }

    
    @Column(name="FEHCA_REGISTRO", length=7)
    public Date getFehcaRegistro() {
        return this.fehcaRegistro;
    }
    
    public void setFehcaRegistro(Date fehcaRegistro) {
        this.fehcaRegistro = fehcaRegistro;
    }

    
    @Column(name="OBSERVACIONES", length=100)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


