package org.zathura.cuentas.personales;
// Generated 4/04/2012 12:36:59 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CpGrupoMovimiento generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="CP_GRUPO_MOVIMIENTO"
    ,schema="CUENTAPERSONAL"
)
public class CpGrupoMovimiento  implements java.io.Serializable {


     private Long idGrupoMovimiento;
     private CpTipoMovimiento cpTipoMovimiento;
     private String descripcion;
     private String observacion;
     private Set<CpMovimiento> cpMovimientos = new HashSet<CpMovimiento>(0);

    public CpGrupoMovimiento() {
    }

	
    public CpGrupoMovimiento(Long idGrupoMovimiento, CpTipoMovimiento cpTipoMovimiento) {
        this.idGrupoMovimiento = idGrupoMovimiento;
        this.cpTipoMovimiento = cpTipoMovimiento;
    }
    public CpGrupoMovimiento(Long idGrupoMovimiento, CpTipoMovimiento cpTipoMovimiento, String descripcion, String observacion, Set<CpMovimiento> cpMovimientos) {
       this.idGrupoMovimiento = idGrupoMovimiento;
       this.cpTipoMovimiento = cpTipoMovimiento;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.cpMovimientos = cpMovimientos;
    }
   
     @Id 

    
    @Column(name="ID_GRUPO_MOVIMIENTO", unique=true, nullable=false, precision=22, scale=0)
    public Long getIdGrupoMovimiento() {
        return this.idGrupoMovimiento;
    }
    
    public void setIdGrupoMovimiento(Long idGrupoMovimiento) {
        this.idGrupoMovimiento = idGrupoMovimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_MOVIMIENTO", nullable=false)
    public CpTipoMovimiento getCpTipoMovimiento() {
        return this.cpTipoMovimiento;
    }
    
    public void setCpTipoMovimiento(CpTipoMovimiento cpTipoMovimiento) {
        this.cpTipoMovimiento = cpTipoMovimiento;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="OBSERVACION", length=50)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cpGrupoMovimiento")
    public Set<CpMovimiento> getCpMovimientos() {
        return this.cpMovimientos;
    }
    
    public void setCpMovimientos(Set<CpMovimiento> cpMovimientos) {
        this.cpMovimientos = cpMovimientos;
    }




}


