package org.zathura.cuentas.personales;
// Generated 4/04/2012 12:36:59 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CpMovimiento generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="CP_MOVIMIENTO"
    ,schema="CUENTAPERSONAL"
)
@SequenceGenerator(name = "movimintoIdSec", sequenceName = "SEC_CPMOVIMIENTO")
public class CpMovimiento  implements java.io.Serializable {


     private Long idMovimiento;
     private CpUsuarios cpUsuarios;
     private CpGrupoMovimiento cpGrupoMovimiento;
     private String descripcionMovimiento;
     private String observaciones;
     private Set<CpDetalleMovimiento> cpDetalleMovimientos = new HashSet<CpDetalleMovimiento>(0);

    public CpMovimiento() {
    }

	
    public CpMovimiento(Long idMovimiento, CpUsuarios cpUsuarios, CpGrupoMovimiento cpGrupoMovimiento) {
        this.idMovimiento = idMovimiento;
        this.cpUsuarios = cpUsuarios;
        this.cpGrupoMovimiento = cpGrupoMovimiento;
    }
    public CpMovimiento(Long idMovimiento, CpUsuarios cpUsuarios, CpGrupoMovimiento cpGrupoMovimiento, String descripcionMovimiento, String observaciones, Set<CpDetalleMovimiento> cpDetalleMovimientos) {
       this.idMovimiento = idMovimiento;
       this.cpUsuarios = cpUsuarios;
       this.cpGrupoMovimiento = cpGrupoMovimiento;
       this.descripcionMovimiento = descripcionMovimiento;
       this.observaciones = observaciones;
       this.cpDetalleMovimientos = cpDetalleMovimientos;
    }
   
     @Id
     @GeneratedValue(generator = "movimintoIdSec")
     @Column(name="ID_MOVIMIENTO", unique=true, nullable=false, precision=22, scale=0)
    public Long getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(Long idMovimiento) {
        this.idMovimiento = idMovimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public CpUsuarios getCpUsuarios() {
        return this.cpUsuarios;
    }
    
    public void setCpUsuarios(CpUsuarios cpUsuarios) {
        this.cpUsuarios = cpUsuarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_GRUPO_MOVIMIENTO", nullable=false)
    public CpGrupoMovimiento getCpGrupoMovimiento() {
        return this.cpGrupoMovimiento;
    }
    
    public void setCpGrupoMovimiento(CpGrupoMovimiento cpGrupoMovimiento) {
        this.cpGrupoMovimiento = cpGrupoMovimiento;
    }

    
    @Column(name="DESCRIPCION_MOVIMIENTO", length=50)
    public String getDescripcionMovimiento() {
        return this.descripcionMovimiento;
    }
    
    public void setDescripcionMovimiento(String descripcionMovimiento) {
        this.descripcionMovimiento = descripcionMovimiento;
    }

    
    @Column(name="OBSERVACIONES", length=50)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cpMovimiento")
    public Set<CpDetalleMovimiento> getCpDetalleMovimientos() {
        return this.cpDetalleMovimientos;
    }
    
    public void setCpDetalleMovimientos(Set<CpDetalleMovimiento> cpDetalleMovimientos) {
        this.cpDetalleMovimientos = cpDetalleMovimientos;
    }




}


