package org.zathura.cuentas.personales;
// Generated 4/04/2012 12:36:59 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CpTipoMovimiento generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="CP_TIPO_MOVIMIENTO"
    ,schema="CUENTAPERSONAL"
)
public class CpTipoMovimiento  implements java.io.Serializable {


     private Long idTipoMovimiento;
     private String descripcion;
     private String observacion;
     private Set<CpGrupoMovimiento> cpGrupoMovimientos = new HashSet<CpGrupoMovimiento>(0);

    public CpTipoMovimiento() {
    }

	
    public CpTipoMovimiento(Long idTipoMovimiento) {
        this.idTipoMovimiento = idTipoMovimiento;
    }
    public CpTipoMovimiento(Long idTipoMovimiento, String descripcion, String observacion, Set<CpGrupoMovimiento> cpGrupoMovimientos) {
       this.idTipoMovimiento = idTipoMovimiento;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.cpGrupoMovimientos = cpGrupoMovimientos;
    }
   
     @Id 

    
    @Column(name="ID_TIPO_MOVIMIENTO", unique=true, nullable=false, precision=22, scale=0)
    public Long getIdTipoMovimiento() {
        return this.idTipoMovimiento;
    }
    
    public void setIdTipoMovimiento(Long idTipoMovimiento) {
        this.idTipoMovimiento = idTipoMovimiento;
    }

    
    @Column(name="DESCRIPCION", length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="OBSERVACION", length=50)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cpTipoMovimiento")
    public Set<CpGrupoMovimiento> getCpGrupoMovimientos() {
        return this.cpGrupoMovimientos;
    }
    
    public void setCpGrupoMovimientos(Set<CpGrupoMovimiento> cpGrupoMovimientos) {
        this.cpGrupoMovimientos = cpGrupoMovimientos;
    }




}


