package org.zathura.cuentas.personales;
// Generated 4/04/2012 12:36:59 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CpUsuarios generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="CP_USUARIOS"
    ,schema="CUENTAPERSONAL"
)
public class CpUsuarios  implements java.io.Serializable {


     private Long idUsuario;
     private String nombre;
     private String apellido;
     private String correo;
     private String contrasena;
     private Long movil;
     private String activo;
     private String observaciones;
     private Set<CpMovimiento> cpMovimientos = new HashSet<CpMovimiento>(0);

    public CpUsuarios() {
    }

	
    public CpUsuarios(Long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public CpUsuarios(Long idUsuario, String nombre, String apellido, String correo, String contrasena, Long movil, String activo, String observaciones, Set<CpMovimiento> cpMovimientos) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.contrasena = contrasena;
       this.movil = movil;
       this.activo = activo;
       this.observaciones = observaciones;
       this.cpMovimientos = cpMovimientos;
    }
   
     @Id 

    
    @Column(name="ID_USUARIO", unique=true, nullable=false, precision=22, scale=0)
    public Long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="NOMBRE", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDO", length=50)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="CORREO", length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="CONTRASENA", length=50)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="MOVIL", precision=22, scale=0)
    public Long getMovil() {
        return this.movil;
    }
    
    public void setMovil(Long movil) {
        this.movil = movil;
    }

    
    @Column(name="ACTIVO", length=1)
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }

    
    @Column(name="OBSERVACIONES", length=50)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cpUsuarios")
    public Set<CpMovimiento> getCpMovimientos() {
        return this.cpMovimientos;
    }
    
    public void setCpMovimientos(Set<CpMovimiento> cpMovimientos) {
        this.cpMovimientos = cpMovimientos;
    }




}


